-- In-app notifications for coffee chats.
--
-- The app deploys as a static site (no server runtime, no cron, no service
-- role, no email), so there are two delivery paths, both driven by the anon
-- client under RLS:
--
--   * Reminders are generated by the RECIPIENT's own browser when they open the
--     app near a meeting, so they self-insert (RLS insert policy restricted to
--     type = 'reminder' addressed to self). A partial unique index makes the
--     insert idempotent — re-opening the app never duplicates a reminder.
--
--   * Cross-user event notices (a booking, a cancellation, a location change)
--     are addressed to the OTHER party, which a plain client insert must not be
--     allowed to do. They go through a SECURITY DEFINER RPC that reads the
--     coffee_chats seat row, proves the caller is a party to it, and derives
--     the recipient from the row — never from client-supplied ids.

create table if not exists public.notifications (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users (id) on delete cascade, -- recipient
  type           text not null check (type in (
                    'reminder',
                    'chat_booked',
                    'chat_cancelled_by_applicant',
                    'chat_cancelled_by_host',
                    'location_added',
                    'location_updated'
                  )),
  title          text not null,
  body           text,
  coffee_chat_id uuid references public.coffee_chats (id) on delete set null,
  meeting_time   timestamptz,
  member_id      uuid,   -- the host, for context / deep-linking
  actor_id       uuid,   -- who caused it (null for self-generated reminders)
  read           boolean not null default false,
  created_at     timestamptz not null default now()
);

-- Newest-first fetch for the panel.
create index if not exists notifications_user_created
  on public.notifications (user_id, created_at desc);

-- Fast unread-badge count.
create index if not exists notifications_user_unread
  on public.notifications (user_id) where read = false;

-- Idempotent client reminders: at most one reminder per (recipient, meeting).
-- PARTIAL on type = 'reminder' so multi-seat 'chat_booked' notices to the same
-- host at the same meeting_time (from different applicants) are NOT blocked.
create unique index if not exists notifications_reminder_unique
  on public.notifications (user_id, meeting_time) where type = 'reminder';

alter table public.notifications enable row level security;

-- Owner reads own notifications.
drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
on public.notifications
for select to authenticated
using ( user_id = auth.uid() );

-- Owner may update own rows (used to flip `read`). RLS can't diff OLD vs NEW,
-- so this technically allows editing other columns too; the blast radius is
-- self-only since a user only owns notifications addressed to them. A BEFORE
-- UPDATE trigger restricting changes to `read` is optional hardening.
drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own"
on public.notifications
for update to authenticated
using ( user_id = auth.uid() )
with check ( user_id = auth.uid() );

-- Owner may insert ONLY self-addressed reminders (client-generated). Every
-- other type must go through the SECURITY DEFINER RPC below.
drop policy if exists "notifications_insert_self_reminder" on public.notifications;
create policy "notifications_insert_self_reminder"
on public.notifications
for insert to authenticated
with check ( user_id = auth.uid() and type = 'reminder' );

-- Owner may dismiss (delete) own notifications.
drop policy if exists "notifications_delete_own" on public.notifications;
create policy "notifications_delete_own"
on public.notifications
for delete to authenticated
using ( user_id = auth.uid() );

-- Cross-user notification insert for coffee-chat events. The caller passes the
-- coffee_chats seat id; recipient/actor/context are derived from that row, and
-- the caller must be a party to it. CALL THIS BEFORE a release UPDATE (while
-- the row still binds both parties); for 'chat_booked' call it AFTER the claim
-- (the row already binds applicant = caller).
create or replace function public.notify_coffee_chat_counterparty(
  p_chat_id uuid,
  p_type    text,
  p_message text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_member    uuid;
  v_applicant uuid;
  v_time      timestamptz;
  v_dur       int;
  v_recipient uuid;
  v_title     text;
  v_body      text;
  v_when      text;
begin
  select member_id, applicant_id, meeting_time, duration_minutes
    into v_member, v_applicant, v_time, v_dur
    from public.coffee_chats
   where id = p_chat_id;

  if not found then
    raise exception 'coffee chat % not found', p_chat_id;
  end if;

  -- Authorize and set direction from the row, never from client-supplied ids.
  if auth.uid() = v_member and p_type in ('chat_cancelled_by_host', 'location_added', 'location_updated') then
    v_recipient := v_applicant;
  elsif auth.uid() = v_applicant and p_type in ('chat_booked', 'chat_cancelled_by_applicant') then
    v_recipient := v_member;
  else
    raise exception 'not authorized to notify for this chat, or type mismatch';
  end if;

  if v_recipient is null then
    return; -- open seat: nobody to notify
  end if;

  v_when := to_char(v_time, 'Dy Mon FMDD, FMHH12:MI AM');

  v_title := case p_type
    when 'chat_booked'                 then 'New coffee chat booked'
    when 'chat_cancelled_by_applicant' then 'Coffee chat cancelled'
    when 'chat_cancelled_by_host'      then 'Your coffee chat was cancelled'
    when 'location_added'              then 'Coffee chat location added'
    when 'location_updated'            then 'Coffee chat location updated'
  end;

  v_body := case p_type
    when 'chat_booked'                 then 'Someone booked your ' || v_dur || '-min slot on ' || v_when || '.'
    when 'chat_cancelled_by_applicant' then 'Your ' || v_dur || '-min slot on ' || v_when || ' is open again.'
    when 'chat_cancelled_by_host'      then 'Your host cancelled the ' || v_dur || '-min chat on ' || v_when || '.'
    when 'location_added'              then 'A location was set for your chat on ' || v_when || '.'
    when 'location_updated'            then 'The location changed for your chat on ' || v_when || '.'
  end;

  if p_message is not null and length(trim(p_message)) > 0 then
    v_body := v_body || ' Message: ' || trim(p_message);
  end if;

  insert into public.notifications
    (user_id, type, title, body, coffee_chat_id, meeting_time, member_id, actor_id)
  values
    (v_recipient, p_type, v_title, v_body, p_chat_id, v_time, v_member, auth.uid());
end;
$$;

grant execute on function public.notify_coffee_chat_counterparty(uuid, text, text) to authenticated;
